### ISSUE TITLE
Please add "Eggs and bacon" to the menu

### ISSUE THREAD

**Issue by josmiseth** [equinor/MamasKitchen#106]

**Comment by olvemaudal** [comment]
That was an excellent idea!

**Comment by olvemaudal** [comment]
I discussed it with my brothers, and they loved the suggestion. We fixed in https://github.com/equinor/MamasKitchen/commit/0c04d5d48479dd290f3b64c76357164d4a99c954

**Comment by josmiseth** [comment]
Great! Thanks!

**Comment by SondreTor** [comment]
I hate eggs

**Comment by ingunnr** [comment]
:-) (Y)

**Comment by UlrichTheune** [comment]
Are these organic eggs?

**Comment by dtb102** [comment]
Make sure the eggs are free-range

**Comment by hflesche** [comment]
What about eggs, spam, spam and eggs?
