### ISSUE TITLE
Potato dumplings please

### ISSUE THREAD

**Issue by oyskjaevel** [equinor/MamasKitchen#109]

**Comment by olvemaudal** [comment]
Nice suggestion. I will discuss it with Mama.

**Comment by olvemaudal** [comment]
Thank you. Mama and my brothers loved the idea. I fixed it in https://github.com/equinor/MamasKitchen/commit/628b17be752b18f74510f9bef0084241f00f7aea

**Comment by oyskjaevel** [comment]
Thanks!
