### ISSUE TITLE
Please remove tomates from the Omelette

### ISSUE THREAD

**Issue by grykristin** [equinor/MamasKitchen#124]
Original dish:
Omelette with bacon and mushrooms and tomatoes

**Comment by olvemaudal** [comment]
Why?

**Comment by grykristin** [comment]
Tomatoes makes the omelette "soggy"

**Comment by olvemaudal** [comment]
I see. I will fix later....

**Comment by olvemaudal** [comment]
Or, btw, can you make that change yourself?
