### ISSUE TITLE
Remove apple from pizza

### ISSUE THREAD

**Issue by runejo85** [equinor/MamasKitchen#191]
Apple does not belong on pizza

**Comment by nordbo** [comment]
![bdownload](https://user-images.githubusercontent.com/535114/150299961-bef61f68-7eec-4622-a3e1-ce2361253bf4.jpg)
Why not replace apples with banana?

**Comment by olvemaudal** [comment]
+1 Great suggestion Rune. Looking forward to more improvements from you. See you on monday!
