### ISSUE TITLE
Add more diet-friendly desserts to the menu

### ISSUE THREAD

**Issue by Shotscape** [equinor/MamasKitchen#220]
![image](https://user-images.githubusercontent.com/93441247/175894482-f94eea27-273b-499f-88b9-fd0eecb7a596.png)

**Comment by olvemaudal** [comment]
Thanks for your suggestion. Can you please provide the receipt?

**Comment by Shotscape** [comment]
Thanks for your reply @olvemaudal ! Here it is:

https://www.today.com/recipes/joy-bauer-s-watermelon-dessert-pizza-recipe-t161231
