### ISSUE TITLE
New dessert

### ISSUE THREAD

**Issue by AlineMelchuna** [equinor/MamasKitchen#233]
Include "Brigadeiro" on dessert!

**Comment by olvemaudal** [comment]
Can you please provide a receipt for that? A link for example?

**Comment by AlineMelchuna** [comment]
Brazilian dessert!! Mama should try, here it is the link for recipe: https://tasty.co/recipe/classic-brigadeiros !!

**Comment by olvemaudal** [comment]
Nice! I will give it a try. Stay tuned!
