### ISSUE TITLE
Please make me a smoothe asap

### ISSUE THREAD

**Issue by mohjorth** [equinor/MamasKitchen#29]

**Comment by mohjorth** [comment]
Blueberry

**Comment by olvemaudal** [comment]
I can't make you a smoothe right now, but at least I added it to the dessert menu. https://github.com/equinor/MamasKitchen/commit/05fcde2562c4ddf0db2997b0005ca50f8560b24f#diff-c10f72a638faf6d9923d3bf7d6fa4705

Hope this resolves the issue. Feel free to reopen if you disagree.
