### ISSUE TITLE
Det mangler salt-feskball på menyen!

### ISSUE THREAD

**Issue by oeda** [equinor/MamasKitchen#30]

**Comment by HildeGlomstad** [comment]
med ketchup takk! :)

**Comment by HildeGlomstad** [comment]
![image](https://user-images.githubusercontent.com/69899437/90624707-aabfa400-e218-11ea-887f-716406c7b115.png)

**Comment by olvemaudal** [comment]
Vakkert! Ja, nå er salt-feskbaill inne på menyen, så da er det bare å glede seg.
